spring.application.name=test-rest-java-api
server.port=8080
management.endpoints.web.exposure.include=health,info
spring.jmx.enabled=false
spring.main.lazy-initialization=true
spring.threads.virtual.enabled=true
